import 'package:flutter/material.dart';

const Color khintColor = Color.fromARGB(255, 120, 120, 120);
const Color kGrayColor = Color(0xffF2F2F2);
const String kKeepMeLoggedIn = 'KeepMeLoggedIn';
const String admin = 'admin22';
const String kIsAdmin = 'IsAdmin';
bool isAdmin = false;
const String kProductsCollection = 'products';
String kProductCreatedAt = 'createdAt';
const String kProductDescription = 'description';
const String kProductName = 'name';
const String kProductCategory = 'category';
const String kProductPrice = 'price';
const String kProductQuantity = 'quantity';
const String kProductReviewersNum = 'reviewersNum';
const String kProductReviewsSum = 'reviewsSum';
const String kProductImageUrl = 'imageUrl';
const String kUsersCollection = 'users';
const String kUserName = 'name';
const String kUserPhone = 'phone';
const String kUserAddress = 'address';
