// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7ToLqslPHv-XlTbBzJicdDULvqvqscA',
    appId: '1:864062895552:web:2d7c791fba4bca90d30425',
    messagingSenderId: '864062895552',
    projectId: 'fast-buy-1f3d4',
    authDomain: 'fast-buy-1f3d4.firebaseapp.com',
    storageBucket: 'fast-buy-1f3d4.appspot.com',
    measurementId: 'G-DY0BCH0KS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAufNFjHPekUrf5UGl183wtoohqSmtvg',
    appId: '1:864062895552:android:0ef870b997deb5e8d30425',
    messagingSenderId: '864062895552',
    projectId: 'fast-buy-1f3d4',
    storageBucket: 'fast-buy-1f3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2rdP7NTimywIiNu3Ft_3LLgX2XTzfnA',
    appId: '1:864062895552:ios:7b2a219beecfea1ed30425',
    messagingSenderId: '864062895552',
    projectId: 'fast-buy-1f3d4',
    storageBucket: 'fast-buy-1f3d4.appspot.com',
    iosBundleId: 'com.example.fastBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU2rdP7NTimywIiNu3Ft_3LLgX2XTzfnA',
    appId: '1:864062895552:ios:f19598bb3868bab8d30425',
    messagingSenderId: '864062895552',
    projectId: 'fast-buy-1f3d4',
    storageBucket: 'fast-buy-1f3d4.appspot.com',
    iosBundleId: 'com.example.fastBuy.RunnerTests',
  );
}
